main: lf.jaime.LightFly
version: 1.1.1
api-version: 1.13
author: Jaime
name: LightFly
libraries:
  - com.fasterxml.jackson.core:jackson-databind:2.15.2
commands:
  fly:
    description: Fly command
  lightfly:
    description: Main command
  tempfly:
    description: Temporary flight command

