main: lf.jaime.LightFly
version: 1.0.4
api-version: 1.13
author: Jaime
name: LightFly
commands:
  fly:
    description: Fly command
  lightfly:
    description: Main command
  tempfly:
    description: Temporary flight command

